/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    products: Product;
    pages: Page;
    medias: Media;
    preferences: Preference;
    users: User;
    components: Component;
    'page-social-media-sharing': PageSocialMediaSharing;
    variables: Variable;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'brand-detail': BrandDetail;
    logos: Logo;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  thumbnail: string | Media;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medias".
 */
export interface Media {
  id: string;
  name?: string | null;
  alt: string;
  url: string;
  sizes?: {
    icon: {
      url: string;
    },
    thumbnail: {
      url: string;
    }
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  root?: boolean | null;
  path: string;
  type: 'PAGE' | 'FOLDER';
  children?: (string | Page)[] | null;
  component?: (string | null) | Component;
  favicon?: string | Media;
  title: string;
  description?: string;
  'page-social-media-sharing'?: (string | null) | PageSocialMediaSharing;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "components".
 */
export interface Component {
  id: string;
  name: string;
  props: {
    [k: string]: unknown;
  };
  children?: (string | Component)[] | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-social-media-sharing".
 */
export interface PageSocialMediaSharing {
  id: string;
  title: string;
  description: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preferences".
 */
export interface Preference {
  id: string;
  user: string | User;
  language?: ('en' | 'nl') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  role: 'master' | 'owner' | 'admin' | 'author' | 'visitor';
  modules: ('main' | 'ecommerce')[];
  profileImage?: (string | null) | Media;
  preferences?: (string | null) | Preference;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variables".
 */
export interface Variable {
  id: string;
  name: string;
  'text-value'?: string | null;
  'number-value'?: number | null;
  'color-value'?: string | null;
  type: 'COLOR' | 'TEXT' | 'NUMBER';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-detail".
 */
export interface BrandDetail {
  id: string;
  name: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos".
 */
export interface Logo {
  id: string;
  logoIcon?: (string | null) | Media;
  'favicon-default': string | Media;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
