export const DEFAULT_PANEL_LAYOUT = [
    20,
    60,
    20
];

export const PLACEHOLDER_ID = "PLACEHOLDER";

export const NEW_COMPONENT_PLACEHOLDER_ID_PREFIX = "NEW_COMPONENT_PLACEHOLDER-";
export const NEW_COMPONENT_ID_PREFIX = "NEW_COMPONENT-";
